# Generated by Django 2.1.5 on 2019-01-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('comments', models.TextField()),
                ('nodeUUID', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('itr', models.PositiveSmallIntegerField(default=4)),
                ('taskUUID', models.UUIDField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
