# Generated by Django 2.1.5 on 2019-01-14 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nglogman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgnode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='lgnode',
            name='nodeUUID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
