# Generated by Django 2.1.5 on 2019-01-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nglogman', '0002_auto_20190114_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='itr',
            new_name='interval',
        ),
    ]
