# Generated by Django 2.1.5 on 2019-01-15 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nglogman', '0004_auto_20190115_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGNode',
            fields=[
                ('hostname', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('comments', models.TextField()),
                ('nodeUUID', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskName', models.CharField(max_length=200)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('interval', models.PositiveSmallIntegerField(default=4)),
                ('taskUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
