# Generated by Django 2.1.5 on 2019-01-16 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nglogman', '0005_lgnode_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lgnode',
            options={'verbose_name': 'Logging Node', 'verbose_name_plural': 'Logging Nodes'},
        ),
        migrations.AlterField(
            model_name='lgnode',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lgnode',
            name='nodeUUID',
            field=models.UUIDField(default=uuid.UUID('6ddee3db-f6b0-455f-bd48-93fb6e519e8b'), primary_key=True, serialize=False),
        ),
    ]
